version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../app:/var/www/html
    depends_on:
      - backend
      - frontend

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend
    working_dir: /var/www/html
    volumes:
      - ../app/backend:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:randomkey
    ports:
      - "9000:9000"
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: frontend
    volumes:
      - ../app/frontend:/usr/src/app
    working_dir: /usr/src/app
    stdin_open: true
    tty: true
    ports:
      - "5173:5173"
    depends_on:
      - backend

  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: caballero
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
